# dein itself
[[plugins]]
repo = 'Shougo/dein.vim'

#--------------------------------
# General for coding/writing
#--------------------------------

# enhance syntacs check
[[plugins]]
repo = 'scrooloose/syntastic' 
hook_add = '''
  " let g:syntastic_check_on_open = 1
  " let g:syntastic_check_on_wq = 0
  " highlight SyntasticErrorLine ctermfg=red ctermbg=none
  " highlight SyntasticWarningLine ctermfg=red ctermbg=none
  " let g:syntastic_python_checkers = ['flake8', 'pep8']
  " let g:syntastic_python_pep8_args = '--ignore=E126,E203'
  " let g:syntastic_python_flake8_args = '--ignore=E126,E203'
'''

[[plugins]]
repo = 'vim-scripts/grep.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# quick run
[[plugins]]
repo = 'thinca/vim-quickrun'

# sudo
[[plugins]]
repo = 'sudo.vim'

#---------------------------
# Web Service
#---------------------------

# w3m
[[plugins]]
repo = 'yuratomo/w3m.vim'
