# on_ft
## preview
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['mkd', 'md', 'markdown', 'html']
'depends = ['open-browser.vim', 'webapi-vim']
hook_add = '''
  if !g:not_isbow
    let g:previm_open_cmd=expand('~/bin/chrome_wrapper')
  endif
  let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_source = ['previm']

[[plugins]]
repo = 'mattn/webapi-vim'
on_source = ['previm', 'esa.vim']

## CPP
[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

## Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#completions_command = '<C-c>'
  let g:jedi#popup_on_dot = 0
  let g:jedi#popup_select_first = 0
'''

## Javascript
[[plugins]]
repo = 'AtsushiSakai/bookmarklet.vim'
on_ft = 'javascript'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
